### ISSUE TITLE
Ti.meteor uses tiws and has problems with tiws 

### ISSUE THREAD

**Issue by AppWerft** [omorandi/tiws#14] opened 2015-01-15 11:35 UTC
Hi Oliver,

currently I'm playing with Ti.Meteor. In the issue tracker (https://github.com/moritzknecht/TiMeteor/issues/2) I found  stories about crashes on iOS. Moritz wrote about PocketSockets and the crashes disappears …… What do you think about crashes and the alternative?

Rainer

**Comment by omorandi** [comment] 2015-01-16 09:30
@AppWerft I think it would be cool having some more info about those crashes ;-)

**Comment by AppWerft** [comment] 2015-01-16 09:34
@omorandi After a little workshop about TiMeteor we think the module is a little immature. The original meteor libs are copied into the module. I think I would copied copy all new versions. It seems to be unsustainable and fragmented. On the other hand: Meteor is great!  Thanks for your answer.

**Comment by omorandi** [comment] 2015-01-16 10:20
Ok, closing this for now

**Closed by omorandi** 2015-01-16 10:20 UTC

**Comment by icellan** [comment] 2015-01-19 00:11
@omorandi @AppWerft I have been using the tiws websocket implementation for some time in my Titanium projects and it has never been 100% stable (version 0.5 by @omorandi is the most stable). The apps have always been plagued by crashes. Granted they have all been talking to a Meteor backend, but I have used multiple implementation on the Titanium Javascript end.

When I replaced tiws with a native Javascript implementation, the crashes did not occur anymore, but this introduced other problems, like no support for large data (images) to be transported over the websocket.

The problems with twis seem to occur mostly when the app is brought back from sleep. So my hunch is that it has something to do with state and unexpected info coming from the server.

**Comment by yuchi** [comment] 2015-01-19 08:39
Can you create a list of issues for your instability? I’d like to set up automated tests so step to reproduce and expected/actual results could help me.

I don’t know how to test the when the app goes to the bg and back to the fg…

**Comment by omorandi** [comment] 2015-01-19 09:11
Yes, I'd be happy to review any crash log hinting that issues come from tiws, but without any (or even minimal steps to reproduce), it's difficult to help.
My aim is to to try to make TiWS a solid, standards-compliant websocket implementation for Ti. In the mid-long term I'm seeing Socket.io, or any other dependent library, being removed from this repository. 
@yuchi, wrt automated testing, I started thinking about that too (see also #16). Let's sync on this

**Comment by icellan** [comment] 2015-01-23 09:57
I've been trying to recreate this issue for a crash log, but have not been able to do that yet (which is a good thing). I have checked with our users and it looks like we have not been getting any crash reports either in the last couple of weeks.
